version: "3"
services:
  app:
      build:
        context: .
        #Yes; it's the same file name
        dockerfile: Docker/Dockerfile.flask.AWS.hosted.DB
      networks:
        - stocksnetwork
      cap_drop:
        - ALL 
  web:
      build:
        context: .
        dockerfile: Docker/Dockerfile.nginx
      depends_on:
        - app
      ports:
        - "80:8080"
      networks:
        - stocksnetwork 
      cap_drop:
        - ALL 
  db:
      build:
        context: .
        dockerfile: Docker/Dockerfile.mongod
      networks:
        - stocksnetwork 
      cap_drop:
        - ALL 

networks:
  stocksnetwork:
    driver: bridge
