version: "3"
services:
  app:
      build:
        context: .
        dockerfile: Docker/Dockerfile.flask
      networks:
        - stocksnetwork
      cap_drop:
        - ALL 
  web:
      build:
        context: .
        dockerfile: Docker/Dockerfile.nginx
      depends_on:
        - app
      ports:
        - "80:8080"
      networks:
        - stocksnetwork 
      cap_drop:
        - ALL 
  db:
      build:
        context: .
        dockerfile: Docker/Dockerfile.mongod
      networks:
        - stocksnetwork 
      cap_drop:
        - ALL 
  crawler:
      build:
        context: .
        dockerfile: Docker/Dockerfile.crawler.all.date
      networks:
        - stocksnetwork
      cap_drop:
        - ALL



networks:
  stocksnetwork:
    driver: bridge
