version: "3"
services:
  app:
      image: u2f_app_dev
      build:
        context: .
        dockerfile: Docker/Dockerfile.flask.dev
      networks:
        - stocksnetwork
      cap_drop:
        - ALL
  web:
      image: u2f_web_dev
      build:
        context: .
        dockerfile: Docker/Dockerfile.nginx
      depends_on:
        - app
      ports:
        - "127.0.0.1:80:8080"
      networks:
        - stocksnetwork
      cap_drop:
        - ALL
  db:
      image: u2f_db_dev
      build:
        context: .
        dockerfile: Docker/Dockerfile.mongod
      networks:
        - stocksnetwork
      cap_drop:
        - ALL

networks:
  stocksnetwork:
    driver: bridge
