version: "3"
services:
  app:
      build:
        context: .
        dockerfile: Docker/Dockerfile.flask
      networks:
        - stocksnetwork
      cap_drop:
        - ALL 
      environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  web:
      build:
        context: .
        dockerfile: Docker/Dockerfile.nginx
      depends_on:
        - app
      ports:
        - "80:8080"
      networks:
        - stocksnetwork 
      cap_drop:
        - ALL 
networks:
  stocksnetwork:
    driver: bridge
