version: "3"
services:
  crawler:
      build:
        context: .
        dockerfile: Docker/Dockerfile.crawler.flywheel
      networks:
        - stocksnetwork
      logging:
        driver: awslogs
        options:
          awslogs-region: $AWS_REGION
          awslogs-group: crawler
      cap_drop:
        - ALL
networks:
  stocksnetwork:
    driver: bridge
