version: "3"
services:
  db:
     build:
       context: .
       dockerfile: Docker/Dockerfile.mongod
     volumes:
       - data:/data/db
     networks:
       - stocknetwork
     cap_drop:
       - ALL 
     container_name: db
     image: db
  app:
      build:
        context: .
        dockerfile: Docker/Dockerfile.flask.local
      depends_on:
        - db
      networks:
        - stocknetwork
      cap_drop:
        - ALL 
      container_name: app
      image: app
  web:
      build:
        context: .
        dockerfile: Docker/Dockerfile.nginx
      depends_on:
        - app 
      ports: 
        - "80:8080"
      networks:
        - stocknetwork
      cap_drop:
        - ALL 
      container_name: web
      image: web

volumes:
  data:
networks:
  stocknetwork:
    driver: bridge
