FROM python:3.9-slim-bullseye

COPY install-packages.sh .
RUN ./install-packages.sh

ENV WORKDIR /stocks
ENV USER nobody

RUN mkdir $WORKDIR && mkdir $WORKDIR/.aws && chown nobody: $WORKDIR/.aws
RUN usermod -d $WORKDIR -s /bin/bash $USER

COPY requirements.txt /$WORKDIR/

RUN pip install --upgrade pip && pip3 install -r /$WORKDIR/requirements.txt && rm -rf  /root/.cache
RUN mkdir /$WORKDIR/non-app/ &&  mkdir /$WORKDIR/static/ && mkdir /$WORKDIR/templates/ && mkdir /$WORKDIR/lib/
RUN mkdir -p /$WORKDIR/external/gunicorn/

COPY static/                                                           /$WORKDIR/static/
COPY non-app/                                                          /$WORKDIR/non-app/
COPY templates/                                                        /$WORKDIR/templates/
COPY .my.env init.yaml stock_flask.py                                  /$WORKDIR/
COPY external/gunicorn/gunicorn.conf.py                                /$WORKDIR/external/gunicorn/
COPY Docker/flask-docker-entrypoint.sh                                 /usr/sbin/flask-docker-entrypoint.sh
RUN chmod 755                                                          /usr/sbin/flask-docker-entrypoint.sh
RUN ln -s /usr/local/bin/python3.9                                     /usr/bin/python3
COPY lib/                                                              /$WORKDIR/lib/
RUN  chown -R nobody:                                                  /$WORKDIR/

USER $USER
ENTRYPOINT ["/usr/sbin/flask-docker-entrypoint.sh"]
EXPOSE 8000
