name: Dev Docker Nginx Image CI

on:
  push:
    branches:
      - develop
jobs:
  build_image_and_push_to_ecr:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the GitHub Repo
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::631686326988:role/EC2AppRole
        role-duration-seconds: 1200
        role-session-name: MySessionName


    - name: Login to Amazon ECR
      id: jouell-stocks
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build and tag Web image 
      env:
        ECR_REGISTRY: ${{ steps.jouell-stocks.outputs.registry }}
        ECR_REPOSITORY: docker-stocks-web
        IMAGE_TAG: latest 
      run: |
        docker pull      $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker image tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG docker_stocks_web:latest 


    - name: Build and tag App image 
      env:
        ECR_REGISTRY: ${{ steps.jouell-stocks.outputs.registry }}
        ECR_REPOSITORY: docker_stocks_app 
        IMAGE_TAG: latest 
      run: |
        docker pull      $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker image tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG docker_stocks_app:latest 
        docker-compose -f docker-compose.AWS.hosted.MongoDb.yaml up -d 
        docker ps
        docker images
