# https://towardsaws.com/build-push-docker-image-to-aws-ecr-using-github-actions-8396888a8f9e
name: Docker Nginx Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Docker image
      uses: actions/checkout@v2

   - uses: actions/checkout@master
     with:
       name: jouellnyc/AWS
       ref: refs/heads/release
       path: '/tmp/AWS/'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: jouell-stocks
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag image 
      env:
        ECR_REGISTRY: ${{ steps.jouell-stocks.outputs.registry }}
        ECR_REPOSITORY: docker-stocks-web 
        IMAGE_TAG: latest 
      run: |
        #docker build  --file Docker/Dockerfile.nginx -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker-compose -f docker-compose.local.yaml  build
        docker-compose -f docker-compose.local.yaml  up -d
        docker ps
        docker images
        ls -ltr /tmp/AWS

