# https://towardsaws.com/build-push-docker-image-to-aws-ecr-using-github-actions-8396888a8f9e
name: Docker Nginx Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build Image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Docker image
      uses: actions/checkout@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.jouell-stocks.outputs.registry }}
        ECR_REPOSITORY: docker-stocks-web 
        IMAGE_TAG: latest 
      run: |
        docker build  --file Docker/Dockerfile.nginx -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
