#!/bin/bash

user=jouellnyc
repo=DockerStocksWeb
gh api repos/$user/$repo/actions/runs \
--paginate -q '.workflow_runs[] | select(.head_branch == "develop") | "\(.id)"' | \
xargs -n1 -I % gh api repos/$user/$repo/actions/runs/% -X DELETE
