name: Docker Image CI Build and Push to AWS ECR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: echo 
      run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}
