name: Nginx Docker Image Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: docker build . --file ../Docker/Dockerfile.nginx --tag docker-stocks-web-nginx:$(date +%s)
    - name: Push 
      id: jouell-stocks 
      uses: actions/checkout@v2
      with: 
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        local-image: my-image:v1
        image: my-image:v1, my-image:latest
